/* 
【开头概述】
这个文件是自动生成的“全局组件类型声明文件”。
它告诉 TypeScript：项目里有哪些组件可以在模板中直接使用，
这样在写 <ArticleList /> 之类的组件时能有智能提示和类型检查。
*/

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/*
【主体详解】
declare module 'vue' 是“模块补充声明”（module augmentation）。
意思是：在原本的 vue 类型基础上，额外追加一些你项目里的类型。
*/
declare module 'vue' {
  /*
  GlobalComponents 是 Vue 约定的一个接口：
  里面的每一项都是“全局组件名 -> 组件类型”的映射。
  这样你不用 import 就能在模板里直接用它们。
  */
  export interface GlobalComponents {
    // 这里每个属性名就是你在模板里用的标签名
    // typeof import(... )['default'] 表示：拿到组件文件默认导出的类型
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ArticlePagination: typeof import('./src/components/ArticlePagination.vue')['default']
    ArticlePreview: typeof import('./src/components/ArticlePreview.vue')['default']
    ArticleToggle: typeof import('./src/components/ArticleToggle.vue')['default']
    AuthPage: typeof import('./src/components/AuthPage.vue')['default']
    DeleteArticleButton: typeof import('./src/components/DeleteArticleButton.vue')['default']
    EditArticleButton: typeof import('./src/components/EditArticleButton.vue')['default']
    ErrorMessages: typeof import('./src/components/ErrorMessages.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    // RouterLink / RouterView 是 vue-router 自带的全局组件
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./src/components/TagList.vue')['default']
  }
}

/*
【结尾总结】
这个文件的作用就是：
把项目里的全局组件“登记到类型系统中”，
让模板中直接使用组件时有提示、也能避免拼写错误。
它是自动生成的，所以一般不手动改。
*/